### PR TITLE
Chore/codebase clean

### PR DESCRIPTION
**Pull request by janakan2466**
# Chore

## Codebase clean
The pull request contains the following changes:
- Fix of a pre-commit config file
- A single pass run of linting, formatting, and testing over the entire codebase against default standards
- Enforces code standards upon each commit

## Tests conducted
- End-to-end testing were completed on staging environments

### CODE REVIEW

**Review by markcoatsworth — APPROVED** [review]
Thanks for the code cleanup, looks good to me. @jwilles any opinions on this big linting/cleanup commit?

**Comment by markcoatsworth** [comment]
@janakan2466 I missed the merge conflicts in a handful of files mentioned at the bottom, can you look into these please?

**Comment by janakan2466** [comment]
Done.

**Comment by markcoatsworth** [comment]
I'm just going to merge this for now and fix the test later. The gateway container works fine locally so I'm not too worried about it, besides I expect other things will break when we cut a release branch and need fixing.

**Pull request merged**
