### PR TITLE
Feature/batch-inference

### PR DESCRIPTION
**Pull request by xeon27**
# PR Type ([Feature | Fix | Documentation | Test])
Feature

## Short Description
Batch-Inference (not async) - Support to make generation and activation retrieval requests in batches

## Tests Added
...

### CODE REVIEW

**Review by markcoatsworth — APPROVED** [review]
LGTM. From what I can tell, this is mostly just renaming `prompt` to `prompts` and updated the OPT model_service code to support multiple prompts? Assuming it's all tested and working well then I'm good with this.

**Comment by jwilles** [comment]
The changes also look good to me. One thing to note is that it changes the meaning of the generation request record. We need to add timestamps to that table regardless so let's evaluate then but we will likely want to capture some more metadata about the requests.

**Comment by xeon27** [comment]
@markcoatsworth - That's correct.
@jwilles - Do we need to add timestamps and metadata as part of this PR?

**Review by jwilles — APPROVED** [review]

**Comment by jwilles** [comment]
No let's do it later.

**Comment by markcoatsworth** [comment]
Checks still failing but we'll deal with those later, need to cut a release, merging now.

**Pull request merged**
